### ISSUE TITLE
Default keybinding conflicts with source control

### ISSUE THREAD

**Issue by andys8** [jammerware/code-guid#1]
### Issue

The default keybinding on linux is `Ctrl + Shift + G, Ctrl + Shift + G`. This is in conflict with the Version Control Tab.

![image](https://user-images.githubusercontent.com/13085980/46731950-5c403680-cc8c-11e8-836b-daec7acd0ebb.png)
![image](https://user-images.githubusercontent.com/13085980/46731969-6b26e900-cc8c-11e8-879c-efbd2e6e669f.png)

### Solution

1. Ignore
2. Explain changing the keybinding in `README.md`
3. Switch the default keybinding to a different combination

**Comment by jammerware** [comment]
Thanks for bringing this to my attention. As soon as I get a moment, I'll probably change the default and make a note about the change in the README for existing users. Much appreciated!

**Comment by jammerware** [comment]
Resolved in 308b00f8d3149bb20cbad1207f55a561187c38fa. This has been published to the marketplace as v1.2.1.

Thanks again!
